#!/bin/bash
set -x
if which apt &>/dev/null && [[ -d /var/lib/dpkg && -d /etc/apt ]] ; then
    apt-get update
    echo "işlem başladı....."
    apt install xorriso grub-pc-bin grub-efi mtools make python3 dosfstools e2fsprogs squashfs-tools python3-yaml gcc wget curl unzip xz-utils debootstrap git erofs-utils zstd -y
fi
apt-get install git devscripts equivs -y
#------------------------------------------------------------------------------------
rootfs="distro/rootfs"
rm -rf distro/iso
rm -rf $rootfs
mkdir -p distro
mkdir -p $rootfs/bin
#export PATH=/bbin:$PATH
cp busybox $rootfs/bin/busybox
cd $rootfs/bin/
#busybox --install -s ./
cd $rootfs/
mkdir  -p var run dev sys proc etc tmp/bps/kur
bash -c "echo '127.1.1.0 basitdagitim' >> etc/hosts"
bash -c "echo 'basitdagitim' > etc/hostname"
bash -c "echo 'nameserver 8.8.8.8' > etc/resolv.conf"

### system chroot  bind/mount
#for i in dev dev/pts proc sys; do mount -o bind /$i $rootfs/$i; done
### manuel bps-tools install
$rootfs/bin/busybox wget -O $rootfs/tmp/base-file-1.0.bps https://github.com/basitdagitim/bps-binary-packages/raw/master/sys/base/base-file/base-file-1.0.bps 1>$rootfs/dev/null 2>$rootfs/dev/null
$rootfs/bin/busybox tar -xf $rootfs/tmp/base-file-1.0.bps -C $rootfs/tmp/bps/kur
$rootfs/bin/busybox tar -xf $rootfs/tmp/bps/kur/rootfs.tar.xz -C $rootfs

#paket adresi ekleniyor
$rootf/bin/busybox mkdir -p $rootfs/etc/bps
echo "basitdagitim/bps-binary-packages">$rootfs/etc/bps/sources.list
### installing bps package in rootfs
$rootfs/bin/bps -u $rootfs

$rootfs/bin/bps -ri glibc $rootfs
for paket in pcre2 libselinux libsepol libsemanage mcstrans attr busybox \
		readline ncurses \bash kmod eudev util-linux \grep \sed \
		grub e2fsprogs libarchive xz curl openssl initramfs-tools \gzip \
		coreutils acl gmp findutils openrc audit pam libcap \
		zlib zstd libxml2 brotli curl linux-image  live-boot live-config parted dosfstools
do 
$rootfs/bin/bps -ri $paket $rootfs; 
done


### update-initrd
fname=$(basename $rootfs/boot/config*)
kversion=${fname:7}
mv $rootfs/boot/config* $rootfs/boot/config-$kversion
cp $rootfs/boot/config-$kversion $rootfs/etc/kernel-config
chroot $rootfs update-initramfs -u -k $kversion

#### system chroot umount
#for dir in dev dev/pts proc sys ; do    while umount -lf -R $rootfs/$dir 2>/dev/null ; do true; done done

#************************iso *********************************
mkdir -p distro/iso
mkdir -p distro/iso/boot
mkdir -p distro/iso/boot/grub
mkdir -p distro/iso/live || true

#### Copy kernel and initramfs (Debian/Devuan)


cp -pf $rootfs/boot/initrd.img-* distro/iso/boot/initrd.img
cp -pf $rootfs/boot/vmlinuz-* distro/iso/boot/vmlinuz
rm -rf $rootfs/boot
#### Create squashfs
mksquashfs $rootfs distro/filesystem.squashfs -comp xz -wildcards
mv distro/filesystem.squashfs distro/iso/live/filesystem.squashfs

#### Write grub.cfg

echo 'menuentry "Disk GNU/Linux 64-bit" --class liveiso  {' > distro/iso/boot/grub/grub.cfg
echo '    linux /boot/vmlinuz boot=live net.ifnames=0 biosdevname=0 init=/bin/initdisk ' >> distro/iso/boot/grub/grub.cfg
echo '    initrd /boot/initrd.img' >> distro/iso/boot/grub/grub.cfg
echo '}' >> distro/iso/boot/grub/grub.cfg

echo 'menuentry "Kur iki Part GNU/Linux 64-bit" --class liveiso  {' >> distro/iso/boot/grub/grub.cfg
echo '    linux /boot/vmlinuz boot=live init=/bin/kur2 ' >> distro/iso/boot/grub/grub.cfg
echo '    initrd /boot/initrd.img' >> distro/iso/boot/grub/grub.cfg
echo '}' >> distro/iso/boot/grub/grub.cfg


grub-mkrescue distro/iso/ -o distro/distro.iso

